//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCantine.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cantineEntities : DbContext
    {
        public cantineEntities()
            : base("name=cantineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_activite> tbl_activite { get; set; }
        public virtual DbSet<tbl_adresse> tbl_adresse { get; set; }
        public virtual DbSet<tbl_facture> tbl_facture { get; set; }
        public virtual DbSet<tbl_personne> tbl_personne { get; set; }
        public virtual DbSet<tbl_prix_repas> tbl_prix_repas { get; set; }
        public virtual DbSet<tbl_repas> tbl_repas { get; set; }
        public virtual DbSet<tbl_type_personne> tbl_type_personne { get; set; }
        public virtual DbSet<tbl_historique_facture> tbl_historique_facture { get; set; }
        public virtual DbSet<tbl_relation_activite> tbl_relation_activite { get; set; }
        public virtual DbSet<tbl_relation_repas> tbl_relation_repas { get; set; }
        public virtual DbSet<tbl_utilisateur> tbl_utilisateur { get; set; }
    }
}
