//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCantine.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cantineEntities : DbContext
    {
        public cantineEntities()
            : base("name=cantineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activite> activite { get; set; }
        public virtual DbSet<adresse> adresse { get; set; }
        public virtual DbSet<facture> facture { get; set; }
        public virtual DbSet<personne> personne { get; set; }
        public virtual DbSet<prix_repas> prix_repas { get; set; }
        public virtual DbSet<repas> repas { get; set; }
        public virtual DbSet<type_personne> type_personne { get; set; }
        public virtual DbSet<historique_facture> historique_facture { get; set; }
        public virtual DbSet<relation_activite> relation_activite { get; set; }
        public virtual DbSet<relation_repas> relation_repas { get; set; }
        public virtual DbSet<utilisateur> utilisateur { get; set; }
    }
}
