//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCantine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class relation_activite
    {
        public System.DateTime date_debut { get; set; }
        public Nullable<System.DateTime> date_fin { get; set; }
        public int personne_id { get; set; }
        public byte activite_id { get; set; }
    
        public virtual activite activite { get; set; }
        public virtual personne personne { get; set; }
    }
}
