//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCantine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_utilisateur
    {
        public string pseudo { get; set; }
        public string mdp { get; set; }
        public string mdp_controle { get; set; }
        public string droits { get; set; }
        public bool etat { get; set; }
        public int personne_id { get; set; }
    
        public virtual tbl_personne tbl_personne { get; set; }
    }
}
