//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCantine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_relation_activite
    {
        public System.DateTime date_debut { get; set; }
        public Nullable<System.DateTime> date_fin { get; set; }
        public int personne { get; set; }
        public byte activite { get; set; }
    
        public virtual tbl_activite tbl_activite { get; set; }
        public virtual tbl_personne tbl_personne { get; set; }
    }
}
