//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCantine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_historique_facture
    {
        public int facture { get; set; }
        public int tuteur { get; set; }
        public bool statut_payement { get; set; }
        public bool statut_envoye { get; set; }
        public bool detaille { get; set; }
        public string format_envoye { get; set; }
        public string archive { get; set; }
    
        public virtual tbl_facture tbl_facture { get; set; }
        public virtual tbl_personne tbl_personne { get; set; }
    }
}
