//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCantine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_activite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_activite()
        {
            this.tbl_relation_activite = new HashSet<tbl_relation_activite>();
        }
    
        public byte id { get; set; }
        public string type_activite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_relation_activite> tbl_relation_activite { get; set; }
    }
}
