//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCantine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_relation_repas
    {
        public System.DateTime date_repas { get; set; }
        public int personne { get; set; }
        public int repas { get; set; }
    
        public virtual tbl_personne tbl_personne { get; set; }
        public virtual tbl_repas tbl_repas { get; set; }
    }
}
